on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

name: RA web-ui Build

jobs:
  ghcr:
    name: Docker build and push to ghcr.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3   
      - name: Docker Build
        run: |
          ls -ltr
